# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Keystone driver
#

TARGET_MODULE:=keystone

obj-y += $(TARGET_MODULE).o

$(TARGET_MODULE)-objs += keystone.o keystone-page.o keystone-ioctl.o keystone-enclave.o keystone-sbi.o
